name: PR Template Handler

on:
  pull_request:
    types: [labeled]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Update PR Description
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        LABEL_NAME="${{ github.event.label.name }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"

        if [ "$LABEL_NAME" = "wizard" ]; then
          TEMPLATE_PATH=".github/templates/wizardTemplate.md"
        else
          exit 0
        fi

        PR_TEMPLATE=$(cat $TEMPLATE_PATH)

        # Update the PR description using the GitHub API
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
          -d "$(jq -n --arg body "$PR_TEMPLATE" '{body: $body}')"
